baseURL = "https://example.com/"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "personal-web"
title = "Ryan Portfolio Site"

[params.intro]
main = "Hi, I'm Ryan Sault :shark:"
sub = "I'm *not* a serial killer (We think)"

[params.main]
latestPublishHeader = "My Most Recent Trip"

[taxonomies]
design = "designs"
tech = "techs"

[blackfriday]
hrefTargetBlank = true

[params]
accentColor = "#FD3519" 
breadcrumb = true 
mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404           
rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
gopher = "/images/gopher.png" # checkout https://gopherize.me/
h1 = 'Bummer!' 
p = "It seems that this page doesn't exist." 

[params.sections]
# Define how your sections will be called
# when automatically pulled. For instance in the 404 page
portfolio = "project"
post = "article"

[params.sidebar]
backgroundImage = '/images/background.jpeg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
logo = "/images/turtle.jpg" # - default "/images/edna-west.jpg"
[params.assets]
customCSS = ""
favicon = ""

[params.social]
codepen = "https://codepen.io/"
facebook = "https://www.facebook.com/"
github = "https://github.com/"
gitlab = "https://gitlab.com/"
instagram = "https://www.instagram.com/"
keybase = "https://keybase.io/"
linkedin = "https://www.linkedin.com/in/"
medium = "https://medium.com/"
twitter = "https://twitter.com/"
youtube = "https://www.youtube.com/"

[params.contact]
email = "ryans_email_whatever@idkthisshit.com" 
text = "" # text of the contact link in the sidebar. If email params.contact.email is defined

[menu]

[[menu.main]]
identifier = "about"
name = "About"
title = "About section"
url = "/about/"
weight = -120

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
title = "Portfolio"
url = "/portfolio/"
weight = -110

[[menu.main]]
identifier = "blog"
name = "Post"
title = "Blog section"
url = "/post/"
weight = -100

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.twitter]
disable = false
enableDNT = true
simple = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
